#ifndef LIBQJSONRPC_GLOBAL_H
#define LIBQJSONRPC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQJSONRPC_LIBRARY)
#  define LIBQJSONRPCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBQJSONRPCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQJSONRPC_GLOBAL_H
